### ISSUE TITLE
API - Get summary state for confidence voting events

### ISSUE THREAD

**Issue by yoda-da** [neelix-io/neelix-experiences#15]
Would like a Get method for stats on the back of a confidence voting event so that I can build an simple two-dimensional dashboard table - milestone/date by net sentiment. I would be useful to know the number of users voted as well.

**Comment by neelix-admin** [comment]
Thank you for submission. We will triage the request and advise on the implementation approach and timelines.

**Comment by neelix-services** [comment]
This is now available. Please refer to https://api.neelix.io/docs/
