### ISSUE TITLE
Retrospective - Ability to edit/hide summary statistics bullet points in the Executive Report

### ISSUE THREAD

**Issue by sergeyburenkov-da** [neelix-io/neelix-experiences#18]
When creating an executive report of a retro (Information -> Summary), the system automatically generates some summary statistics (e.g. "Net impact is between 0 and +6").  It would be useful to be able to edit and/or hide these when adding additional notes, in order to curate these m ore for the clients.

**Comment by neelix-services** [comment]
Thank you for the request. The enhancement is implemented and deployed to production.
In order to toggle statistics per theme row:
- Click on the hamburger icon button located next to the "Summary" heading
- Tick on/off the "Statistics" option
