### ISSUE TITLE
Consortium select dropdown does not display a scroll bar - user has perception that not all items are in the list

### ISSUE THREAD

**Issue by yoda-da** [neelix-io/neelix-experiences#4]
Incident:

- User could not see a particular consortium in the list when navigating to `consortium select` component

Root cause:

- No issue with permissions or data return
- However, the drop down component did not provide a hit that the list is scrollable

Fix:
- Implemented rule to always show scrollbar where appropriate

**Comment by neelix-admin** [comment]
Thank you for report. Issue is now rectified.
