### ISSUE TITLE
Slack and MS Teams integrations - capability to post periodic experiences summary to a nominated channel

### ISSUE THREAD

**Issue by yoda-da** [neelix-io/neelix-experiences#7]
Hi Team,

We would like a capability to post periodic experiences summary to a nominated channel.

- Ability to configure multiple scheduling rules per channel and experiences criteria
- Ability to trigger the rule manually

**Comment by neelix-admin** [comment]
Great idea! Will push it high enough in the backlog.

**Comment by neelix-admin** [comment]
This feature is now implemented in following fashion:
- Fully integrated capability for Slack
- MS Teams does not provide a good scheduling capability as of now; Neelix supports user controlled and admin controlled reminders via email
