### ISSUE TITLE
Registering in confidence voting - organisation default

### ISSUE THREAD

**Issue by drewharding-da** [neelix-io/neelix-experiences#8]
When I register a confidence vote my company defaulted the first time to my company but then on subsequent confidence votes my company was blank. I didn't realise because it had defaulted the first time.

It would be good if the behaviour was consistent in either way for the first time and subsequent times, although my personal preference would be that the company is populated by default.

**Comment by neelix-admin** [comment]
Thank you for the feedback. Will prioritise.

**Comment by neelix-admin** [comment]
Change is implemented and deployed:

- Last selected Team and Visibility options will be remembered within the current activity confidence voting session
